version: '3.9'
services:

  main:
    build:
      context: .
      dockerfile: ./apps/main/Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${MAIN_PORT}:${MAIN_PORT}

  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      target: development
    command: npm run start:dev admin
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}

  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}

  mongodb:
    image: mongo:latest
    env_file:
      .env
    environment:
      - name=value
    volumes:
      - ./mongo-data:/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}

  rabbitmq:
    image: rabbitmq
    env_file:
      - .env
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq/
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
  
  # redis:
  #   image: redis
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./redis-data:/data
  #   ports:
  #     - ${REDIS_PORT}:${REDIS_PORT}
