version: '3.9'
services:

  main:
    build:
      context: .
      dockerfile: ./apps/main/Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${MAIN_PORT}:${MAIN_PORT}

  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      target: development
    command: npm run start:dev admin
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}

  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}

  mongodb-primary:
    image: docker.io/bitnami/mongodb:5.0
    env_file:
      - .env
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:5.0
    env_file:
      - .env
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:5.0
    env_file:
      - .env
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  rabbitmq:
    image: rabbitmq
    env_file:
      - .env
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq/
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
  
  # redis:
  #   image: redis
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./redis-data:/data
  #   ports:
  #     - ${REDIS_PORT}:${REDIS_PORT}
